# ------------------------------------------------------------------------------
# Trivadis - Part of Accenture, Platform Factory - Data Platforms
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ------------------------------------------------------------------------------
# Name.......: Dockerfile
# Author.....: Stefan Oehrli (oes) stefan.oehrli@accenture.com
# Editor.....: Stefan Oehrli
# Date.......: 2023.04.27
# Revision...: 0.1.0
# Purpose....: Dockerfile to build a openconnect image with SSH Deamon
# Notes......: --
# Reference..: --
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ------------------------------------------------------------------------------
# Modified...:
# see git revision history for more information on changes/updates
# ------------------------------------------------------------------------------
version: '3'
services:

# single tenant database
  vpn:
    container_name: openconnect
    image: oehrlis/openconnect:latest
    privileged: true
    volumes:
      - $DOCKER_VOLUME_BASE/authorized_keys:/home/vpn/.ssh/authorized_keys:rw
      - $DOCKER_VOLUME_BASE/vpn.config:/vpn/vpn.config:ro
      - $DOCKER_VOLUME_BASE/vpnpasswd:/vpn/passwd:ro
      - $DOCKER_VOLUME_BASE/vpntoken:/vpn/token:rw
    ports:
      - $SSH_PORT:22
    cap_add:
      - NET_ADMIN
# - EOF ------------------------------------------------------------------------